# Generated by Django 4.2.2 on 2023-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencias',
            fields=[
                ('rol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('caratulado', models.CharField(max_length=50)),
                ('tribunal', models.CharField(max_length=30)),
                ('fecha_sentencia', models.DateField()),
                ('tipo_causa', models.CharField(choices=[('1', 'Consulta'), ('2', 'Demanda'), ('3', 'Reclamación'), ('4', 'Solicitudes')], max_length=20)),
                ('competencia', models.CharField(max_length=25)),
                ('materia', models.CharField(max_length=20)),
                ('ministro_redactor', models.CharField(max_length=25)),
                ('url_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='descriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Jurisprudencias', models.ManyToManyField(to='jurisprudencias_app.jurisprudencias')),
            ],
        ),
    ]
