# Generated by Django 4.2.2 on 2023-06-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisprudencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptores',
            options={'verbose_name': 'Descriptor', 'verbose_name_plural': 'Descriptores'},
        ),
        migrations.AlterModelOptions(
            name='jurisprudencias',
            options={'verbose_name': 'Jurisprudencia', 'verbose_name_plural': 'Jurisprudencias'},
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='fecha_sentencia',
            field=models.CharField(max_length=30),
        ),
    ]
