# Generated by Django 4.2.2 on 2023-06-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisprudencias_app', '0003_alter_jurisprudencias_caratulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='competencia',
            field=models.CharField(max_length=50),
        ),
    ]
