# Generated by Django 4.2.2 on 2023-06-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisprudencias_app', '0005_alter_jurisprudencias_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisprudencias',
            name='url_doc',
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='ministro_redactor',
            field=models.CharField(max_length=50),
        ),
    ]
