# Generated by Django 4.2.2 on 2023-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisprudencias_app', '0007_alter_jurisprudencias_caratulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='tipo_causa',
            field=models.CharField(max_length=20),
        ),
    ]
