# Generated by Django 4.2.2 on 2023-06-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisprudencias_app', '0008_alter_jurisprudencias_tipo_causa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='descriptores',
        ),
    ]
