# Generated by Django 4.2.2 on 2023-06-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesiones_app', '0002_alter_concesiones_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesiones',
            name='numero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesiones',
            name='numero_concesion',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concesiones',
            name='tipo_concesion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesiones',
            name='tipo_tramite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesiones',
            name='tipo_vigencia',
            field=models.CharField(max_length=100),
        ),
    ]
