# Generated by Django 4.2.2 on 2023-06-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesiones_app', '0003_alter_concesiones_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesiones',
            name='tipo_concesion',
            field=models.CharField(max_length=150),
        ),
    ]
