# Generated by Django 4.2.2 on 2023-06-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesiones_app', '0008_alter_concesiones_comuna_alter_concesiones_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesiones',
            name='concesionario',
            field=models.CharField(max_length=150),
        ),
    ]
