# Generated by Django 4.2.2 on 2023-06-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesiones_app', '0009_alter_concesiones_concesionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesiones',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
